BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB


BBBBB BBBBB XXXXX BBBBBBBB


BBBBB BBBB
    XXXXXXXXX XXXXXXXXX
    XXXXX XXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        FFFFFF
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
BBBBBBBB