# Generated by Django 4.0.2 on 2023-09-23 17:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='short description')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description of product')),
                ('image', models.ImageField(blank=True, upload_to='product/product_pic', verbose_name='product picture')),
                ('old_price', models.PositiveIntegerField(verbose_name='old price')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateTime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='DateTime Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='comment')),
                ('stars', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'very good')], max_length=10, verbose_name='stars')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DateTime Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='DateTime Modified')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product', verbose_name='product')),
            ],
        ),
    ]
