# Generated by Django 4.0.2 on 2023-09-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='نظر شما'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'خیلی بد'), ('2', 'بد'), ('3', 'معمولی'), ('4', 'خوب'), ('5', 'خیلی خوب')], max_length=10, verbose_name='امتیاز'),
        ),
    ]
